[project_definition]
binary_path = "./a3"
makefile_path = "."
make_targets = ["all"]
project_name = "A3"
global_timeout = 20

[[testcases]]
name = "Welcome Message"
description = "The test checks if the welcome message is printed correctly, and the quit command works properly."
type = "OrdIO"
io_file = "./tests/01/io.txt"
io_prompt = "^\\s*>\\s*$"
exp_exit_code = 0

[[testcases]]
name = "Shopping list name"
description = "Add a name to the shopping list and quit."
type = "OrdIO"
io_file = "./tests/02/io.txt"
io_prompt = "^\\s*>\\s*$"
exp_exit_code = 0

[[testcases]]
name = "Multiple items"
description = "Add multiple items to the list and quit."
type = "OrdIO"
io_file = "./tests/03/io.txt"
io_prompt = "^\\s*>\\s*$"
exp_exit_code = 0

[[testcases]]
name = "Integer parsing"
description = "Check if the input quantity input field is converted to an integer."
type = "OrdIO"
io_file = "./tests/04/io.txt"
io_prompt = "^\\s*>\\s*$"
exp_exit_code = 0

[[testcases]]
name = "Full shopping list"
description = "Check the flow of a complete program with printing."
type = "OrdIO"
io_file = "./tests/05/io.txt"
io_prompt = "^\\s*>\\s*$"
exp_exit_code = 0

[[testcases]]
name = "Case-sensitive"
description = "All inputs should be handled case-sensitive."
type = "OrdIO"
io_file = "./tests/06/io.txt"
io_prompt = "^\\s*>\\s*$"
exp_exit_code = 0

[[testcases]]
name = "Sorting"
description = "Test the sorting of the item names by their ASCII values"
type = "OrdIO"
io_file = "./tests/07/io.txt"
io_prompt = "^\\s*>\\s*$"
exp_exit_code = 0
